add translations
vtex-apps/order-placed pull request #126
Opened 2020-09-29 15:16 UTC by dvm1984

#### What is the purpose of this pull request?
<add missing translations

2020-10-02 17:31 UTC, klzns approved these changes

2020-10-02 18:02 UTC, kaisermann approved these changes

2020-10-02 18:50 UTC, icazevedo approved these changes

2020-10-05 18:33 UTC, iaronaraujo approved these changes

2020-10-06 14:35 UTC, salesfelipe requested changes
Missing some keys:

![Screen Shot 2020-10-06 at 11 33 53 AM](https://user-images.githubusercontent.com/3926634/95215993-faa5fa80-07c7-11eb-8529-83b5cb96f324.png)

2020-10-14 13:41 UTC, kaisermann commented
@dvm1984 would you be able to add those missing keys @salesfelipe mentioned above?

2024-08-26 17:47 UTC, closed without merging