displayMyOrdersButton & displayUpdateOrderButton props
vtex-apps/order-placed pull request #128
Opened 2020-10-14 09:08 UTC by khrizzcristian

#### What is the purpose of this pull request?
- displayMyOrdersButton prop to op-order-options. Show or hide "My orders" button from Order placed page. (default true)
- displayUpdateOrderButton prop to op-order-options. Show or hide "Update Order" button from Order placed page. (default true)

#### What problem is this solving?
It allows us to hide the "update order" and "my orders" buttons if we don't want them on the page

#### How should this be manually tested?
Working example: https://csss--melimeloparis.myvtex.com/checkout/orderPlaced/?og=v536599meli&__bindingAddress=www.melimeloparis.ro/

#### Screenshots or example usage
`"op-order-options": {
     "props": {
          "displayUpdateOrderButton": false,
          "displayMyOrdersButton": false
     }
},`

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-10-14 13:30 UTC, guerreirobeatriz requested changes

2020-10-14 13:30 UTC, guerreirobeatriz commented on docs/README.md
> +| `displayUpdateOrderButton` | `boolean` | Hide or show "Update order" button | `true`       |
```suggestion
| `displayMyOrdersButton` | `boolean` | Whether the `My Orders` button should be displayed (`true`) or not (`false`). | `true`       |
| `displayUpdateOrderButton` | `boolean` | Whether the `Update order` button should be displayed (`true`) or not (`false`). | `true`       |
```

2020-10-20 12:19 UTC, guerreirobeatriz approved these changes

2021-02-05 07:47 UTC, khrizzcristian commented
New test link with displayCancelOrderButton active: https://longo--customsoft.myvtex.com/checkout/orderPlaced/?og=1108320066749

2021-04-07 16:58 UTC, camilavcoutinho approved these changes
For Localization, LGTM!

2021-04-07 18:57 UTC, klzns commented
Thanks for the pull request.

Alternative approach for this issue was created:
https://github.com/vtex-apps/order-details/pull/24

2021-04-07 18:57 UTC, closed without merging