fix: display of bank invoice information
vtex-apps/order-placed pull request #199
Opened 2024-12-27 20:32 UTC by gaboulsvtex

#### What is the purpose of this pull request?

Fix a bug.

#### What problem is this solving?

In orders where the bank invoice payment method wasn't the first payment of the first transaction, its information wasn't displayed at the order placed page

#### How should this be manually tested?
There are 2 use cases for this change:
- Orders with a single transaction with multiple payments, in which the one of them is a bank invoice and it isn't in the first position of the payments array;
- Orders with multiple transactions in which one of them has a bank invoice payment, and this transaction isn't the first of the array.

#### Screenshots or example usage
Example of an order with bank invoice in the second payment of the array, where its information is not displayed
![image](https://github.com/user-attachments/assets/012a2c58-dbeb-4108-9488-31cac4d86500)

#### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2024-12-27 21:48 UTC, iago1501 requested changes
Algumas alterações rápidas de boas práticas/legibilidade, depois de verificado se resolve o problema, vou validar de fato a usabilidade da alteração pra ver o impacto que ela vai ter

2024-12-27 21:48 UTC, iago1501 commented on react/Notices.tsx
> +
```suggestion
 const sortTransactions = (transactions) => {
  return transactions.slice().sort((a, b) => {
    const hasBankInvoiceA = a.payments.some((p) => p.group === 'bankInvoice');
    const hasBankInvoiceB = b.payments.some((p) => p.group === 'bankInvoice');
    return hasBankInvoiceA === hasBankInvoiceB ? 0 : hasBankInvoiceA ? -1 : 1;
  });
};

const sortPayments = (payments) => {
  return payments.slice().sort((a, b) => (a.group === 'bankInvoice') - (b.group === 'bankInvoice'));
};

const updatedOrders = orders.map((order) => ({
...order,
  paymentData: {
...order.paymentData,
    transactions: sortTransactions(order.paymentData.transactions).map((transaction) => ({
...transaction,
      payments: sortPayments(transaction.payments),
    })),
  },
}));

```

Mantendo imutabilidade da variável original

2024-12-27 21:48 UTC, iago1501 commented on react/Notices.tsx
>    const bankInvoice = orders
```suggestion
  const bankInvoice = updatedOrders
```

2024-12-27 21:48 UTC, iago1501 commented on manifest.json
> +  "version": "2.18.1",
```suggestion
  "version": "2.18.0",
```

O CI/CD faz a atualização de forma automática depois de escolher o versionamento

2025-01-07 14:21 UTC, gaboulsvtex commented on react/Notices.tsx
> +
Obrigado pelas sugestões.
Em meu novo commit eu fiz apenas alguns ajustes em cima da sua sugestão:

- Removi os nested ternaries da linha 69;
- Corrigi a função sortPayments(), que estava invertida e o TypeScript não aceitou a operação aritmética entre booleanos.

2025-01-07 14:25 UTC, gaboulsvtex reviewed
Obrigado pelas sugestões.
Em meu novo commit eu fiz apenas alguns ajustes em cima da sua sugestão:

- Removi os nested ternaries da linha 69;
- Corrigi a função sortPayments(), que estava invertida e o TypeScript não aceitou a operação aritmética entre booleanos.

2025-01-07 20:48 UTC, iago1501 requested changes

2025-01-09 17:42 UTC, iago1501 commented
@gaboulsvtex , eu fiz uma outra proposta de implementação, dado que a ideia de reordenar só seria um workaround pro problema principal (retornar apenas um método de pagamento quando possui vários), se puder checar pra ver se resolve o seu problema, creio que resolvendo, a gente encerra esse e segue pelo outro: https://github.com/vtex-apps/order-placed/pull/200

2025-01-09 19:07 UTC, closed without merging